### ISSUE TITLE
mdisk bot issue

### ISSUE THREAD

**Issue by SpidyKhrish007** [bipinkrish/Mdisk-Downloader-Bot#43]
hay i am deploying mdisk bot on render.com and cant start the bot idk whats the issue i need help

this is the logs i found in it 

```
**Apr 1 07:58:46 PM  Traceback (most recent call last):
Apr 1 07:58:46 PM    File "/app/main.py", line 43, in <module>
Apr 1 07:58:46 PM      with app: app.set_bot_commands(BotCommand(cmds[i].lower(),descs[i]) for i in range(len(cmds)))
Apr 1 07:58:46 PM    File "/usr/local/lib/python3.9/site-packages/pyrogram/client.py", line 302, in enter
Apr 1 07:58:46 PM      return self.start()
Apr 1 07:58:46 PM    File "/usr/local/lib/python3.9/site-packages/pyrogram/sync.py", line 66, in async_to_sync_wrap
Apr 1 07:58:46 PM      return loop.run_until_complete(coroutine)
Apr 1 07:58:47 PM    File "/usr/local/lib/python3.9/asyncio/base_events.py", line 647, in run_until_complete
Apr 1 07:58:47 PM      return future.result()
Apr 1 07:58:47 PM    File "/usr/local/lib/python3.9/site-packages/pyrogram/methods/utilities/start.py", line 58, in start
Apr 1 07:58:47 PM      is_authorized = await self.connect()
Apr 1 07:58:47 PM    File "/usr/local/lib/python3.9/site-packages/pyrogram/methods/auth/connect.py", line 40, in connect
Apr 1 07:58:47 PM      await self.load_session()
Apr 1 07:58:47 PM    File "/usr/local/lib/python3.9/site-packages/pyrogram/client.py", line 627, in load_session
Apr 1 07:58:47 PM      raise AttributeError("The API key is required for new authorizations. "
Apr 1 07:58:47 PM  AttributeError: The API key is required for new authorizations. More info: https://docs.pyrogram.org/start/auth**
```

getting this error all the time when i deploy the bot help me if youu can

**Comment by bipinkrish** [comment]
You need to set ENV or update json
